import * as echarts from 'echarts';
import { UNITS, WAVES, ENEMIES } from './content';
import type { Role } from './types';

export function mountManual(host: HTMLElement) {
  const roles = Object.keys(UNITS) as Role[];
  let tab = 'waves';
  let rank = 0;
  let chart: echarts.ECharts | null = null;
  host.innerHTML = `<div class="manual-tabs" role="tablist" aria-label="Field intelligence"><button class="quiet" data-tab="waves" role="tab" aria-selected="true">Wave intelligence</button><button class="quiet" data-tab="units" role="tab" aria-selected="false">Soldier comparison</button><button class="quiet" data-tab="research" role="tab" aria-selected="false">Design research</button></div><div id="manual-pane" class="manual-pane" role="tabpanel"></div>`;
  const pane = host.querySelector<HTMLElement>('#manual-pane')!;
  const textStyle = { fontFamily: 'Barlow, sans-serif', fontSize: 18, color: '#bad3e2' };
  function render() {
    chart?.dispose(); chart = null;
    host.querySelectorAll<HTMLElement>('[data-tab]').forEach(button => button.setAttribute('aria-selected', String(button.dataset.tab === tab)));
    if (tab === 'research') {
      pane.innerHTML = `<p>This campaign uses a fixed route, deliberate enemy combinations, and time to plan between waves. The full design report examines 13 primary sources. The rules below are our design conclusions, not copied wave schedules.</p><div class="research-list"><article><h3>Teach, reinforce, test.</h3><p>Introduce a threat in isolation, repeat it with a familiar enemy, then test the combination. Recovery waves create room to rebuild before the next boss.</p><a href="https://media.gdcvault.com/gdc2012/slides/Design%20Track/Fan_George_How%20I%20Got.pdf" target="_blank" rel="noreferrer">George Fan on teaching Plants vs. Zombies</a></article><article><h3>Composition creates decisions.</h3><p>Fast runners pressure coverage. Armor resists small shots. Swarms reward splash. Medics reward target selection. Health increases support those jobs.</p><a href="https://store.steampowered.com/app/246420/Kingdom_Rush/" target="_blank" rel="noreferrer">Kingdom Rush</a></article><article><h3>Luck creates moments.</h3><p>A Gunner's rage lasts five seconds and cannot refresh itself. A Sniper's boss headshot deals five times normal damage. Neither effect is required for the introductory waves.</p><p>At 10% per shot, ten Sniper shots have about a 65% chance of at least one headshot. A boss defense needs a reliable backup.</p></article><article><h3>Every soldier earns a role.</h3><p>Grenadiers clear clusters, Engineers buy firing time, and Officers improve nearby damage. Only the strongest support effect applies. Officers cannot amplify each other.</p><a href="https://github.com/shoemoney/SMA-smtd/blob/main/docs/research/tower-defense-research.md" target="_blank" rel="noreferrer">Read the complete research report</a></article></div><h3>Why this tower-defense format?</h3><p>Fixed routes make range and coverage easy to understand on a phone. Maze-building, action hybrids, and roguelite drafting remain expansion ideas. The first release concentrates on a complete squad and one authored operation. Start with $100. Cadets cost $10; other soldier tiers cost progressively more. Normal kills pay $1 in wave one and gain $1 every three waves. Three airstrikes are shared across the entire run.</p><p class="manual-note">All combat values are starting balance values. Passing the rules tests does not establish that every strategy or difficulty is balanced. The repository contains the playtest and tuning plan.</p><p><a href="https://github.com/shoemoney/SMA-smtd/blob/main/docs/game-design.md" target="_blank" rel="noreferrer">Open the full game design and roadmap</a></p>`;
      return;
    }
    if (tab === 'waves') {
      pane.innerHTML = `<p>Read the composition before you commit. Select a wave in the chart for its briefing. A boss and supporting monsters arrive every five waves. After the first launch, waves start automatically after six-second breaks.</p><div class="manual-chart" role="img" aria-label="Interactive stacked enemy counts for all thirty waves"></div><div id="wave-detail" class="manual-note">Hover or tap a wave to inspect its enemies. Pinch or drag the range selector to inspect a shorter section.</div><details><summary>Open exact wave schedules</summary><div class="manual-table-wrap"><table class="manual-table"><thead><tr><th>Wave</th><th>Operation</th><th>Contacts</th><th>Clear bonus</th></tr></thead><tbody>${WAVES.map(w => `<tr><td>${w.number}</td><td>${w.name}<br>${w.briefing}</td><td>${w.groups.map(g => `${g.count} ${ENEMIES[g.kind].name}`).join('<br>')}</td><td>${w.reward}</td></tr>`).join('')}</tbody></table></div></details><p class="manual-note">These are authored starting values. Counts show composition, not effective difficulty. Enemy health, speed, armor, spacing, and your firing coverage all change the actual threat.</p>`;
      chart = echarts.init(pane.querySelector<HTMLElement>('.manual-chart')!, undefined, { renderer: 'svg' });
      chart.setOption({ backgroundColor: 'transparent', textStyle, animation: false, tooltip: { trigger: 'axis', textStyle: { fontSize: 18 }, backgroundColor: '#102938', borderColor: '#557486', confine: true }, legend: { type: 'plain', top: 0, textStyle, pageTextStyle: textStyle, pageIconColor: '#52caff', itemWidth: 18, itemHeight: 18 }, grid: { left: 65, right: 20, top: 130, bottom: 95 }, xAxis: { type: 'category', data: WAVES.map(w => w.number), name: 'Wave', nameLocation: 'middle', nameGap: 35, nameTextStyle: textStyle, axisLabel: { ...textStyle, interval: 4 } }, yAxis: { type: 'value', name: 'Enemies', nameTextStyle: textStyle, axisLabel: textStyle, splitLine: { lineStyle: { color: '#294958' } } }, dataZoom: [{ type: 'slider', bottom: 0, height: 28, textStyle, borderColor: '#385869', fillerColor: '#2ccaff22', start: 0, end: 100 }], series: Object.entries(ENEMIES).map(([kind, enemy]) => ({ name: enemy.name, type: 'bar', stack: 'contacts', barMaxWidth: 25, itemStyle: { color: enemy.color }, emphasis: { focus: 'series' }, data: WAVES.map(w => w.groups.filter(g => g.kind === kind).reduce((sum, g) => sum + g.count, 0)) })) });
      chart.on('click', params => { if (params.dataIndex !== undefined) { const wave = WAVES[params.dataIndex]; const detail = pane.querySelector('#wave-detail')!; detail.textContent = `Wave ${wave.number}: ${wave.name}. ${wave.briefing} ${wave.lesson}`; } });
    } else {
      pane.innerHTML = `<p>Compare all six soldiers at the same rank. Base damage per second assumes continuous fire at one unarmored target. Special effects are explained separately.</p><div class="manual-options"><label for="manual-rank">Promotion level</label><select id="manual-rank">${[0, 1, 2, 3].map(r => `<option value="${r}" ${r === rank ? 'selected' : ''}>${r === 0 ? 'Base rank' : `Upgrade ${r}`}</option>`).join('')}</select></div><div class="manual-chart" role="img" aria-label="Interactive comparison of soldier damage per second"></div><p class="manual-note">The Gunner's outlined extension is a theoretical long-run estimate with uninterrupted targets and no active-rage rerolls. Sniper boss damage averages 1.4× before armor and overkill. Grenadier splash, Engineer slow, and Officer support are excluded; their benefit depends on placement and enemy density.</p><details><summary>Open all stats and upgrades</summary><div class="manual-table-wrap"><table class="manual-table"><thead><tr><th>Soldier / rank</th><th>Cost</th><th>Damage</th><th>Shots/sec</th><th>Range</th><th>Special</th></tr></thead><tbody>${roles.flatMap(role => UNITS[role].ranks.map((r, i) => `<tr><td>${UNITS[role].name}<br>${i === 0 ? 'Base' : `Upgrade ${i}`} · ${r.name}</td><td>${r.cost}</td><td>${r.damage}</td><td>${r.rate}</td><td>${r.range}m</td><td>${r.splash ? `Splash ${r.splash}m. ` : ''}${r.slow ? `Slow ${Math.round(r.slow * 100)}%. ` : ''}${r.aura ? `Damage aura +${Math.round(r.aura * 100)}%. ` : ''}${UNITS[role].special}</td></tr>`)).join('')}</tbody></table></div></details>`;
      pane.querySelector<HTMLSelectElement>('#manual-rank')!.addEventListener('change', event => { rank = Number((event.target as HTMLSelectElement).value); render(); });
      chart = echarts.init(pane.querySelector<HTMLElement>('.manual-chart')!, undefined, { renderer: 'svg' });
      const base = roles.map(role => UNITS[role].ranks[rank].damage * UNITS[role].ranks[rank].rate);
      const extra = roles.map((role, i) => { const r = UNITS[role].ranks[rank]; return role === 'gunner' ? base[i] * (4 * 5 / (5 + 1 / (.05 * r.rate))) : role === 'sniper' ? base[i] * .4 : 0; });
      chart.setOption({ backgroundColor: 'transparent', textStyle, animation: false, tooltip: { trigger: 'axis', confine: true, textStyle: { fontSize: 18 }, backgroundColor: '#102938', borderColor: '#557486', valueFormatter: (value: number) => `${Number(value).toFixed(1)} damage/sec` }, grid: { left: 10, right: 30, top: 15, bottom: 55, containLabel: true }, xAxis: { type: 'value', name: 'Damage / second', nameLocation: 'middle', nameGap: 35, nameTextStyle: textStyle, axisLabel: textStyle, splitLine: { lineStyle: { color: '#294958' } } }, yAxis: { type: 'category', inverse: true, data: roles.map(role => UNITS[role].name.replace('Machine Gunner', 'Gunner').replace('Combat Engineer', 'Engineer').replace('Field Officer', 'Officer')), axisLabel: textStyle }, series: [{ name: 'Base direct damage', type: 'bar', stack: 'damage', barMaxWidth: 33, data: base.map((value, i) => ({ value, itemStyle: { color: UNITS[roles[i]].color } })) }, { name: 'Estimated special bonus', type: 'bar', stack: 'damage', data: extra.map((value, i) => ({ value, itemStyle: { color: 'transparent', borderColor: UNITS[roles[i]].color, borderWidth: 2, borderType: 'dashed' } })) }] });
    }
  }
  host.querySelectorAll<HTMLElement>('[data-tab]').forEach(button => button.addEventListener('click', () => { tab = button.dataset.tab!; render(); }));
  new ResizeObserver(() => chart?.resize()).observe(host);
  render();
}
